'env':
  'prod':
    'cloud':
      'base_url': 'https://api.sprintboards.io'
      'default_user':
        'password': 'n*H7A7f@&ikbwu'
        'username': 'sennderqa3@gmail.com'
'environment': 'https://api.sprintboards.io'
'environment_type': 'cloud'
'execution_environment': 'prod'
'service_description': 'services/service_description'
'service_payloads': 'services/payloads'
'overwrite_base_url' : false
